package dev.petrov.ymplayer2.designsystem.skin

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp

// Generated by tools/build-brand.py from the approved r5 silhouette.
private const val YM_PATH = "M38.84305,42.00000L24.78988,18.00000L6.78988,18.00000L28.36963,54.00000L25.95487,73.66667L74.53988,18.00000L59.78988,18.00000ZM24.68610,84.00000L41.68610,84.00000L45.16499,55.66667L25.38188,78.33333ZM48.54031,55.80952L81.53988,18.00000L78.03988,18.00000L46.20402,54.47619ZM59.38736,62.00000L76.84305,42.00000L71.68610,84.00000L88.68610,84.00000L96.78988,18.00000L85.03988,18.00000L50.87660,57.14286Z"

internal fun ymBrandLogo(color: Color): ImageVector =
    ImageVector.Builder("YMPlayer", 100.dp, 100.dp, 100f, 100f).apply {
        addPath(PathParser().parsePathString(YM_PATH).toNodes(),
            fill = SolidColor(color), pathFillType = PathFillType.EvenOdd)
    }.build()
