"""Export the approved r5 mark without masks, for SVG, Compose and Android.

Run with Python + shapely + fonttools; render PNGs with render-brand.cjs + sharp.
The historical approved SVG remains in docs/design/2026-10-01-brand-directions.
"""
from pathlib import Path
import math
from shapely.geometry import Polygon, LineString
from shapely.ops import unary_union
from shapely.affinity import affine_transform
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'docs/design/brand'
OUT.mkdir(parents=True, exist_ok=True)
COPPER, BG, INK = '#D77A50', '#191715', '#EFE5D7'
y = Polygon([(5,18),(23,18),(40,42),(58,18),(75,18),(48,54),(48,84),(31,84),(31,54)])
m = Polygon([(48,54),(75,18),(95,18),(95,84),(78,84),(78,42),(63,62)])
cuts = unary_union([LineString([(5.5,110),(95.5,-10)]).buffer(1.4, cap_style='flat'),
                    LineString([(50,60),(102.5,-10)]).buffer(1.4, cap_style='flat')])
mark = affine_transform(unary_union([y,m]).difference(cuts), [1,-math.tan(math.radians(7)),0,1,4,0])
def ring(coords):
    return 'M' + 'L'.join(f'{x:.5f},{y:.5f}' for x,y in list(coords)[:-1]) + 'Z'
path = ''.join(ring(p.exterior.coords) + ''.join(ring(h.coords) for h in p.interiors) for p in mark.geoms)
def svg(body, w, h): return f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}">{body}</svg>\n'
def glyph(color): return f'<path fill="{color}" fill-rule="evenodd" d="{path}"/>'
(OUT / 'ym-logo.svg').write_text(svg(glyph(COPPER),100,100), encoding='utf-8')
(OUT / 'ym-logo-mono.svg').write_text(svg(glyph('white'),100,100), encoding='utf-8')
# Banner lettering is outlined, so installed TV fonts cannot change its layout.
font = TTFont('C:/Windows/Fonts/bahnschrift.ttf')
glyphs, cmap = font.getGlyphSet(), font.getBestCmap()
pen = SVGPathPen(glyphs)
cursor = 0
from fontTools.pens.transformPen import TransformPen
for char in 'YMPlayer 2':
    name = cmap[ord(char)]
    glyphs[name].draw(TransformPen(pen, (1,0,0,1,cursor,0)))
    cursor += glyphs[name].width
scale = 31 / font['head'].unitsPerEm
banner = f'<rect width="640" height="360" fill="{BG}"/>'
banner += f'<g transform="translate(54 72) scale(2.16)">{glyph(COPPER)}</g>'
banner += f'<path fill="{INK}" transform="translate(294 198) scale({scale*2} {-scale*2})" d="{pen.getCommands()}"/>'
(OUT / 'tv-banner.svg').write_text(svg(banner,640,360), encoding='utf-8')
(OUT / 'launcher-preview.svg').write_text(svg(f'<rect width="108" height="108" rx="24" fill="{BG}"/><g transform="translate(20 18) scale(.72)">{glyph(COPPER)}</g>',108,108),encoding='utf-8')

res = ROOT / 'app/src/main/res'
def vector(body, size=108):
    return f'<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="{size}dp" android:height="{size}dp" android:viewportWidth="{size}" android:viewportHeight="{size}">\n{body}\n</vector>\n'
foreground = f'<group android:translateX="20" android:translateY="18" android:scaleX="0.72" android:scaleY="0.72"><path android:fillType="evenOdd" android:fillColor="{COPPER}" android:pathData="{path}"/></group>'
(res / 'drawable/ic_launcher_foreground.xml').write_text(vector(foreground),encoding='utf-8')
(res / 'drawable/ic_launcher.xml').write_text(vector(f'<path android:fillColor="{BG}" android:pathData="M0,0H108V108H0Z"/>{foreground}'),encoding='utf-8')
for qualifier, body in [('mipmap-anydpi','<inset xmlns:android="http://schemas.android.com/apk/res/android" android:drawable="@drawable/ic_launcher"/>'),
                        ('mipmap-anydpi-v26',f'<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android"><background android:drawable="@color/brand_background"/><foreground android:drawable="@drawable/ic_launcher_foreground"/></adaptive-icon>')]:
    (res / qualifier).mkdir(exist_ok=True)
    (res / qualifier / 'ic_launcher.xml').write_text(body+'\n',encoding='utf-8')
(res / 'values/brand.xml').write_text(f'<resources><color name="brand_background">{BG}</color></resources>\n',encoding='utf-8')
kt = ROOT / 'designsystem/src/main/kotlin/dev/petrov/ymplayer2/designsystem/skin/YmBrandLogo.kt'
kt.write_text('''package dev.petrov.ymplayer2.designsystem.skin

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp

// Generated by tools/build-brand.py from the approved r5 silhouette.
private const val YM_PATH = "'''+path+'''"

internal fun ymBrandLogo(color: Color): ImageVector =
    ImageVector.Builder("YMPlayer", 100.dp, 100.dp, 100f, 100f).apply {
        addPath(PathParser().parsePathString(YM_PATH).toNodes(),
            fill = SolidColor(color), pathFillType = PathFillType.EvenOdd)
    }.build()
''',encoding='utf-8')
print('Generated approved r5 negative-space contours and outlined TV banner')
