// npm dependency: sharp. Canonical SVGs are generated by build-brand.py.
const sharp = require('sharp');
const path = require('path');
const fs = require('fs');
const root = path.resolve(__dirname, '..');
const source = path.join(root, 'docs/design/brand');
(async () => {
  for (const [density, width] of [['mdpi',160],['hdpi',240],['xhdpi',320],['xxhdpi',480],['xxxhdpi',640]]) {
    const out = path.join(root,'app/src/main/res',`drawable-${density}`);
    fs.mkdirSync(out,{recursive:true});
    await sharp(path.join(source,'tv-banner.svg')).resize(width,width*9/16).png().toFile(path.join(out,'tv_banner.png'));
  }
  for (const [name,size] of [['tv-banner',1280],['launcher-preview',432],['ym-logo',800]])
    await sharp(path.join(source,name+'.svg')).resize(size).png().toFile(path.join(source,name+'.png'));
})();
